[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]
  directory = "netlify/functions"

[dev]
  autoLaunch = false
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3003
  port = 8888
  publish = "dist"
  functions = "netlify/functions"
  functionsPort = 3001

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://evoucher.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Accept, Origin, X-MBX-APIKEY"
    Access-Control-Allow-Credentials = "true" 